### ISSUE TITLE
请问下这个seetaFace_identification.caffemodel是怎么来的？

### ISSUE THREAD

**Issue by yejingx** [camel007/caffe_seetaFace_Identification#4]
是基于 seeta 的模型转换的吗？还是自己训练的？

谢谢！

**Comment by camel007** [comment]
转换过来的

**Comment by yuchiwang** [comment]
@camel007 请问转换的代码方便提供吗。。。

**Comment by camel007** [comment]
保存到txt然后caafe再读进去    手动的发自我的iPhone------------------ 原始邮件 ------------------发件人: 王宇驰  <notifications@github.com>发送时间: 2017年9月20日 14:29收件人: camel007/caffe_seetaFace_Identification <caffe_seetaFace_Identification@noreply.github.com>抄送: 张垚 <yaozhang.chn@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[camel007/caffe_seetaFace_Identification] 请问下这个seetaFace_identification.caffemodel是怎么来的？ (#4)@camel007 请问转换的代码方便提供吗。。。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/camel007/caffe_seetaFace_Identification","title":"camel007/caffe_seetaFace_Identification","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/camel007/caffe_seetaFace_Identification"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yuchiwang in #4: @camel007 请问转换的代码方便提供吗。。。"}],"action":{"name":"View Issue","url":"https://github.com/camel007/caffe_seetaFace_Identification/issues/4#issuecomment-330757586"}}}
